# .github/workflows/ci-test.yml
name: Run Symfony Tests CI

on:
    push:
        branches: [main]
    pull_request:

jobs:
    symfony-tests:
        runs-on: ubuntu-latest

        env:
            APP_ENV: test
            # Set the database URL to use an in-memory SQLite database for testing
            DATABASE_URL: "sqlite:///:memory:"
            WEATHER_API_KEY: "fake-api-key-for-tests"

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, pdo, pdo_sqlite
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --no-interaction

            - name: Create database schema from mappings
              run: php bin/console doctrine:schema:create --env=test

            - name: Load fixtures
              run: php bin/console doctrine:fixtures:load --env=test --no-interaction

            - name: Run PHPUnit tests
              run: php bin/phpunit --colors=always --no-coverage
