# .github/workflows/ci-test.yml
name: Run Symfony Tests CI

on:
    push:
        branches: [main]
    pull_request:

jobs:
    symfony-tests:
        runs-on: ubuntu-latest

        env:
            APP_ENV: test
            # Set the database URL to use SQLite for testing
            DATABASE_URL: "sqlite:///${{ github.workspace }}/var/test.db"
            WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, pdo, pdo_sqlite
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --no-interaction

            - name: Prepare SQLite test database
              run: |
                  mkdir -p var
                  rm -f var/test.db

            - name: Ensure SQLite file exists
              run: touch var/test.db

            - name: Create database schema from mappings
              run: php bin/console doctrine:schema:create --env=test

            - name: Load fixtures
              run: php bin/console doctrine:fixtures:load --env=test --no-interaction

            - name: Run PHPUnit tests
              run: php bin/phpunit --colors=always --no-coverage
